### PR TITLE
Added filter functionality to Videos

### PR DESCRIPTION
**Pull request by aryanagarwal15**
@Rushi98 please review and merge

### CODE REVIEW

**Comment by PrabhutvaAgrawal** [comment]
The spinner to filter out the creator of the video shows duplicate entries and is not filtering well. Please check it.
Also the scrolling is a bit slow and not smooth.
screenshot_20190220-221159

**Comment by aryanagarwal15** [comment]
@Prabhutva figured.. will fix this.

**Comment by aryanagarwal15** [comment]
@Rushi98 I've fixed both the issue pointed by @Prabhutva. merge when convenient!

**Comment by Rushi98** [comment]
@aryanagarwal15 @Prabhutva continued in #167

**Pull request closed without merging**
