### PR TITLE
Utilities Section remade

### PR DESCRIPTION
**Pull request by aryanagarwal15**
This is in reference to #79 

@Rushi98 Only three things are to be done:
A) I was not sure how to get menus from firebase here in Realm. So I've just created a viewholder and adapter class. You probably can add that logic. Won't take much time.
B) Currently only Taxi no. are visible and I was not able to add logic for scooty and car rental numbers. I really think the approach used in UtilitiesContactsActivity is very bad. Would prefer if it is done better.
C) As I didn't have data for menu currently. I have not implemented pinch to zoom feature in viewholder. Will do that in future commits.

Lets keep this PR active and develop on it. As I require collaborative help, I would appreciate if all the work is done in this PR.

### CODE REVIEW

**Comment by Rushi98** [comment]
screenshot_20180820-233529
screenshot_20180820-233537
@aryanagarwal15 the ui needs improvement,
1. Calculate span count based on device width
2. Make the label height wrap content, max width constant

**Comment by aryanagarwal15** [comment]
@Rushi98 I am not sure if many people use the landscape mode in our Application. We probably can make this landscape only app (Up for discussion). I'll fix UI problems you pointed out in 1st screenshot.

**Comment by Rushi98** [comment]
It's not hard to support landscape grid layout. See how span count was calculated in the code you replaced.

**Comment by Rushi98** [comment]
closing as out-of-date

**Pull request closed without merging**
