### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by hardik124**

### CODE REVIEW

**Comment by hardik124** [comment]
@kukreja-vikramaditya  , I created another pull request squashing commits , please check

**Comment by shreyasnbhat** [comment]
@hardik124 You don't need to close a PR if you are only squashing commits.
You do the rebase in your issue branch and the PR automatically gets updated.
:)

**Comment by kukreja-vikramaditya** [comment]
> I created another pull request squashing commits

Please follow this advice (https://github.com/MobileApplicationsClub/DoJMA/pull/68#issuecomment-296185723) for any new PRs. You can use force push to rewrite branch commit history which automatically updates your PR

```sh
git push -f origin my-fix-branch
```

**Comment by kukreja-vikramaditya** [comment]
1 final change, add this line at the end of your script section
`  - ./gradlew clean build connectedCheck`

Apart from that fix is fine

**Comment by hardik124** [comment]
@kukreja-vikramaditya ./gradlew clean build connectedCheck fails

**Comment by hardik124** [comment]
@kukreja-vikramaditya  , ./gradlew clean build connectedCheck fails.

**Comment by kukreja-vikramaditya** [comment]
@hardik124 
Please stop closing PRs

Also your changes are fine, but the issue is with LeakCanary release builds while `connectedCheck` works. Please create a new issue after understanding the error in travis here https://travis-ci.org/MobileApplicationsClub/DoJMA/builds/224469186#L3463

For more on this issue check 
https://github.com/square/leakcanary/wiki/FAQ#how-many-methods-does-leakcanary-add
https://github.com/square/leakcanary/wiki/FAQ#how-do-i-fix-build-errors

I'll merge the PR for now.

**Comment by hardik124** [comment]
@kukreja-vikramaditya  , when i used force push , it removed all commits hence closing the PR .

**Pull request merged**
