### PR TITLE
Fixed Article Viewer Activity

### PR DESCRIPTION
**Pull request by aryanagarwal15**
This is in reference to #120

### CODE REVIEW

**Comment by Rushi98** [comment]
Doesn't solve the issue.

screenshot_20180723-180542
screenshot_20180723-181046

**Comment by aryanagarwal15** [comment]
@Rushi98 The bug is minimised for now. We can look at this post launch. Almost all the articles are loading fine after this update. I'll update html for this particular article later.

**Comment by aryanagarwal15** [comment]
@tanmaydixit I have changed fonts as requested. Please merge

**Comment by Rushi98** [comment]
@aryanagarwal15 as far as I know, there was only one article with this issue. Making the images smaller does not minimize issue. I've reverted this pr merge. As you've said, the original issue is to be fixed by changing upstream html itself. 

For font changes, create another pr.

**Comment by aryanagarwal15** [comment]
@Rushi98 the issue is not just in one article. Try opening how to survive first month in the campus or 4 years a slave. These two article were fixed by the pr. Also i've made a lot of changes in the layout of article viewer as well. Please check and remerge.

**Pull request merged**
